[build]
  base = "/"
  publish = "dist/"
  command = "npm run build"

# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false

[[redirects]]
  from = "https://wikilear.netlify.app/*"
  to = "https://test.wikilear.it/*"
  status = 301
  force = true