module.exports = [
  {
    title: "Google Apps Script",
    imageUrl: "/images/apps_script_48dp.png",
    imageAlt: "Google Apps Script",
    more: "Articoli e codelab...",
    url: "/google-apps-script/",
  },
  {
    title: "Fogli Google",
    imageUrl: "/images/sheets_48dp.png",
    imageAlt: "Fogli Google",
    more: "Articoli e tutorial...",
    url: "/google-sheets/",
  },
  {
    title: "Documenti Google",
    imageUrl: "/images/docs_48dp.png",
    imageAlt: "Documenti Google",
    more: "Articoli e tutorial...",
    url: "/google-docs/",
  },
  {
    title: "Google Drive",
    imageUrl: "/images/drive_48dp.png",
    imageAlt: "Google Drive",
    more: "Articoli e tutorial...",
    url: "/google-drive/",
  },
  {
    title: "Google Maps",
    imageUrl: "/images/maps_48dp.png",
    imageAlt: "Google Maps",
    more: "Articoli e tutorial...",
    url: "/google-maps/",
  },
  {
    title: "Gmail",
    imageUrl: "/images/gmail_48dp.png",
    imageAlt: "Gmail",
    more: "Articoli e tutorial...",
    url: "/gmail/",
  },
  {
    title: "Eleventy",
    imageUrl: "/images/11ty.svg",
    imageAlt: "Eleventy",
    more: "Articoli e tutorial...",
    url: "/11ty/",
  },
  {
    title: "Tailwind CSS",
    imageUrl: "/images/tailwindcss-mark.svg",
    imageAlt: "Tailwind CSS",
    more: "Articoli e tutorial...",
    url: "/tailwindcss/",
  },
];
